import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Sparkles, Loader2 } from "lucide-react";
import { toast } from "sonner";

interface MagicButtonProps {
  text: string;
  mode?: "rewrite" | "summary";
  context?: string;
  onResult: (improved: string) => void;
  size?: "sm" | "default";
  label?: string;
}

export const MagicButton = ({ text, mode = "rewrite", context, onResult, size = "sm", label = "Magic AI" }: MagicButtonProps) => {
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true);
    try {
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:9000';
      const res = await fetch(`${apiUrl}/api/ai/rewrite`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, mode, context }),
      });

      if (!res.ok) throw new Error("AI failed");
      const { data } = await res.json();
      
      let improvedText;
      if (mode === 'summary') {
        improvedText = data.summary;
      } else {
        improvedText = data.rewritten;
      }
      
      onResult(improvedText);
      toast.success(mode === 'summary' ? "Summary generated by AI" : "Rewritten by AI");
    } catch (e: any) {
      console.error("MagicButton AI Error:", e);
      toast.error(e.message ?? "AI failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button type="button" size={size} variant="outline" onClick={run} disabled={loading}
      className="border-primary/50 text-primary hover:bg-primary/10">
      {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
      {label}
    </Button>
  );
};
